### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by planet4** [satnaing/terminal-portfolio#11]
Thanks for sharing this project. This is not a bug just a question. Tried to run this in my web provider via cpanel but it does not work. But is there any ways of running it in a docker container.  Do you have ang docs that could help me?

**Comment by Manjit2003** [comment]
Ik I am late but just build the project and put the dist folder into the www directory

**Comment by satnaing** [comment]
Sorry, it's been a while.
But, I would do the same as @Manjit2003 if I were in that situation.
